# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(741, 481)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(420, 10, 301, 461))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.txtName = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.txtName.setFont(font)
        self.txtName.setObjectName("txtName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtName)
        self.btnAddParticipant = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.btnAddParticipant.setFont(font)
        self.btnAddParticipant.setObjectName("btnAddParticipant")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.btnAddParticipant)
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.ItemRole.SpanningRole, spacerItem)
        self.verticalLayout.addLayout(self.formLayout)
        self.lblWinner = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.lblWinner.setText("")
        self.lblWinner.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblWinner.setObjectName("lblWinner")
        self.verticalLayout.addWidget(self.lblWinner)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.btnStartDraw = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.btnStartDraw.setFont(font)
        self.btnStartDraw.setObjectName("btnStartDraw")
        self.verticalLayout.addWidget(self.btnStartDraw)
        self.listParticipants = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listParticipants.setGeometry(QtCore.QRect(10, 10, 391, 461))
        self.listParticipants.setObjectName("listParticipants")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Giveaway"))
        self.btnAddParticipant.setText(_translate("MainWindow", "KATILIMCI EKLE"))
        self.label.setText(_translate("MainWindow", "Katılımcı İsmi"))
        self.btnStartDraw.setText(_translate("MainWindow", "ÇEKİLİŞİ BAŞLAT"))
